In [6]:
import numpy as np

In [8]:
x = np.arange(0,60,10)
x.reshape((-1,1))

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [10]:
y=np.arange(0,6)
y.T


array([0, 1, 2, 3, 4, 5])

In [28]:
yT=y.T
np.sum(y,axis=0)
# 两个矩阵相乘
np.dot(y,x)

#构建一个方阵
np.diag(y)


array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [30]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [33]:
np.empty((3,5),np.int32) # 3行5列的矩阵，每个元素的值是随机的

array([[          0, -1342177280,           0, -1342177280,           8],
       [          0,           0,           0,           0,           0],
       [          0,           0,           0,           0,           0]],
      dtype=int32)

In [36]:
np.ones((3,5),np.int32) # 3行5列的矩阵，每个元素的值是1
np.eye(4) # 4行4列的单位矩阵

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
y= x [[0,3,1,5]] # 选取第0行的第3,3,1,5列的元素
y

array([ 0, 30, 10, 50])

In [42]:
[(x>10)&(x<50)] # 选取x中大于10小于50的元素

# matrix multiplication
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.dot(x,y)
v


array([[19, 22],
       [43, 50]])

In [43]:
# vstack 垂直堆叠
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

np.vstack((x,y))

# hstack 水平堆叠
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
# argmax 返回最大值的索引
x = np.array([9,2,3,4,5,6,7,1,11])
print(np.argmax(x))

# argmin 返回最小值的索引
x = np.array([1,-1,3,4,5,6,7,8,9])
print(np.argmin(x))

# argsort 返回排序后的索引
x = np.array([1,2,3,4,5,6,7,8,9])
print(np.argsort(x))



8
1
[0 1 2 3 4 5 6 7 8]


In [5]:
# 将数组保存为文件
x = np.array([1,2,3,4,5,6,7,8,9])
np.save('x.npy',x)

NameError: name 'np' is not defined

In [ ]:
# 读入文件之后自动转换为矩阵
np.loadtxt('data.txt',delimiter=',',dtype=np.int32)