In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
%matplotlib inline

In [2]:
data_ori = pd.read_csv('/Users/mac/Desktop/数据挖掘实验/bankloan.csv')

In [3]:
# 数据预处理
t = data_ori.isnull().sum()
print(t)

A1     12
A2      0
A3      0
A4      6
A5      6
A6      9
A7      9
A8      0
A9      0
A10     0
A11     0
A12     0
A13     0
A14     0
A15     0
A16     0
dtype: int64


In [4]:
print(t[t>0])

A1    12
A4     6
A5     6
A6     9
A7     9
dtype: int64


In [5]:
# 无缺失值
data_ori['A1'].value_counts()

b    468
a    210
Name: A1, dtype: int64

In [6]:
data_ori['A1'].fillna('b',inplace=True) # 用众数填充

In [7]:
data_ori['A4'].value_counts()

u    519
y    163
l      2
Name: A4, dtype: int64

In [8]:
data_ori['A4'].fillna('u',inplace=True) # 用众数填充

In [9]:
data_ori['A5'].value_counts()

g     519
p     163
gg      2
Name: A5, dtype: int64

In [10]:
data_ori['A5'].fillna('g',inplace=True) # 用众数填充

In [11]:
data_ori['A6'].value_counts()

c     137
q      78
w      64
i      59
aa     54
ff     53
k      51
cc     41
m      38
x      38
d      30
e      25
j      10
r       3
Name: A6, dtype: int64

In [12]:
data_ori['A6'].fillna('c',inplace=True) # 用众数填充

In [13]:
data_ori['A7'].value_counts()

v     399
h     138
bb     59
ff     57
j       8
z       8
dd      6
n       4
o       2
Name: A7, dtype: int64

In [14]:
data_ori['A7'].fillna('v',inplace=True) # 用众数填充

In [15]:
data_ori['A9'].value_counts()

t    361
f    329
Name: A9, dtype: int64

In [16]:
data_ori['A9'].fillna('t',inplace=True) # 用众数填充

In [17]:
data_ori['A10'].value_counts()

f    395
t    295
Name: A10, dtype: int64

In [18]:
data_ori['A10'].fillna('f',inplace=True) # 用众数填充

In [19]:
data_ori['A12'].value_counts()

f    374
t    316
Name: A12, dtype: int64

In [20]:
data_ori['A12'].fillna('f',inplace=True) # 用众数填充

In [21]:
data_ori['A13'].value_counts()

g    625
s     57
p      8
Name: A13, dtype: int64

In [22]:
data_ori['A13'].fillna('g',inplace=True) # 用众数填充

In [23]:
cols = ['A1','A4','A5','A6','A7','A9','A10','A12','A13']

In [24]:
for col in cols:
    print( col,'->' ,data_ori[col].unique())

A1 -> ['b' 'a']
A4 -> ['u' 'y' 'l']
A5 -> ['g' 'p' 'gg']
A6 -> ['w' 'q' 'm' 'r' 'cc' 'k' 'c' 'd' 'x' 'i' 'e' 'aa' 'ff' 'j']
A7 -> ['v' 'h' 'bb' 'ff' 'j' 'z' 'o' 'dd' 'n']
A9 -> ['t' 'f']
A10 -> ['t' 'f']
A12 -> ['f' 't']
A13 -> ['g' 's' 'p']


In [25]:
data_ori.shape

(690, 16)

In [26]:
data_ori.head()

A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13  A14  A15  A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202    0    1
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43  560    1
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  280  824    1
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100    3    1
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120    0    1

In [27]:
# 将数值进行数据化
data_ori['A1'] = data_ori['A1'].map({'a':0,'b':1})
data_ori['A4'] = data_ori['A4'].map({'u':0,'y':1,'l':2})
data_ori['A5'] = data_ori['A5'].map({'g':0,'p':1,'gg':2})
data_ori['A6'] = data_ori['A6'].map({'c':0,'d':1,'cc':2,'i':3,'j':4,'k':5,'m':6,'r':7,'q':8,'w':9,'x':10,'e':11,'aa':12,'ff':13})
data_ori['A7'] = data_ori['A7'].map({'v':0,'h':1,'bb':2,'j':3,'n':4,'z':5,'dd':6,'ff':7,'o':8})
data_ori['A9'] = data_ori['A9'].map({'t':0,'f':1})
data_ori['A10'] = data_ori['A10'].map({'t':0,'f':1})
data_ori['A12'] = data_ori['A12'].map({'t':0,'f':1})
data_ori['A13'] = data_ori['A13'].map({'g':0,'p':1,'s':2})


In [28]:
data_ori.head()

A1     A2     A3  A4  A5  A6  A7    A8  A9  A10  A11  A12  A13  A14  A15  \
0   1  30.83  0.000   0   0   9   0  1.25   0    0    1    1    0  202    0   
1   0  58.67  4.460   0   0   8   1  3.04   0    0    6    1    0   43  560   
2   0  24.50  0.500   0   0   8   1  1.50   0    1    0    1    0  280  824   
3   1  27.83  1.540   0   0   9   0  3.75   0    0    5    0    0  100    3   
4   1  20.17  5.625   0   0   9   0  1.71   0    1    0    1    2  120    0   

   A16  
0    1  
1    1  
2    1  
3    1  
4    1

In [29]:
# 查找其中是否还存在缺失值
data_ori.isnull().sum()

A1     0
A2     0
A3     0
A4     0
A5     0
A6     0
A7     0
A8     0
A9     0
A10    0
A11    0
A12    0
A13    0
A14    0
A15    0
A16    0
dtype: int64

In [30]:
target = 'A16'
predictors = [col for col in data_ori.columns if col != target]
predictors

['A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A8',
 'A9',
 'A10',
 'A11',
 'A12',
 'A13',
 'A14',
 'A15']

In [31]:
# 交叉验证
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# Initialize our algorithm

alg = LogisticRegression(random_state=1)
# Compute the accuracy score for all the cross validation folds.  (much simpler than what we did before!)
scores = cross_val_score(alg, data_ori[predictors], data_ori[target], cv=5)
print (scores)
print (scores.std())
# Take the mean of the scores (because we have one for each fold)
print(scores.mean())

[0.70289855 0.87681159 0.92028986 0.76086957 0.86231884]
0.08022233335129302
0.8246376811594203


In [32]:
# 基于随机森林的分类
clf = RandomForestClassifier(n_estimators=120, max_depth=3)
scores = cross_val_score(clf, data_ori[predictors], data_ori[target], cv=5)
print (scores)

[0.67391304 0.96376812 0.89130435 0.8115942  0.89855072]


In [33]:
tree_clf = tree.DecisionTreeClassifier(max_depth=4,criterion='entropy') # 基于决策树的分类
scores = cross_val_score(tree_clf, data_ori[predictors], data_ori[target], cv=5)
print (scores)
print('std= %f' % scores.std())
print (scores.mean())

[0.65217391 0.97101449 0.89130435 0.76086957 0.87681159]
std= 0.111566
0.8304347826086957


In [34]:
# 基于AdaBoost的分类
clf = AdaBoostClassifier(n_estimators=120, algorithm='SAMME')
scores = cross_val_score(clf, data_ori[predictors], data_ori[target], cv=5)
print (scores)
print (scores.std())
print (scores.mean())

[0.66666667 0.96376812 0.9057971  0.76086957 0.9057971 ]
0.10980114159348295
0.8405797101449275


In [35]:
# 比较上面所有提到的模型的性能
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

# Initialize our algorithm
alg = LogisticRegression(random_state=1)
# Compute the accuracy score for all the cross validation folds.  (much simpler than what we did before!)
scores = cross_val_score(alg, data_ori[predictors], data_ori[target], cv=5)
print (scores)

# 基于随机森林的分类
clf = RandomForestClassifier(n_estimators=120, max_depth=3)
scores = cross_val_score(clf, data_ori[predictors], data_ori[target], cv=5)
print (scores)

tree_clf = tree.DecisionTreeClassifier(max_depth=4,criterion='entropy') # 基于决策树的分类
scores = cross_val_score(tree_clf, data_ori[predictors], data_ori[target], cv=5)
print (scores)

# 基于AdaBoost的分类
clf = AdaBoostClassifier(n_estimators=120, algorithm='SAMME')
scores = cross_val_score(clf, data_ori[predictors], data_ori[target], cv=5)
print (scores)

# 画出ROC曲线
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize

# Binarize the output
y = label_binarize(data_ori[target], classes=['-','+'])
n_classes = y.shape[1]

# Split into training and test
X_train, X_test, y_train, y_test = train_test_split(data_ori[predictors], y, test_size=.5,
                                                    random_state=0)

# Learn to predict each class against the other
classifier = OneVsRestClassifier(LogisticRegression(random_state=1))
y_score = classifier.fit(X_train, y_train).decision_function(X_test)

# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()



for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area
fpr["micro"], tpr["micro"], _ = roc_curve(y_test.ravel(), y_score.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])


# Plot of a ROC curve for a specific class
plt.figure()
plt.plot(fpr[2], tpr[2], label='ROC curve (area = %0.2f)' % roc_auc[2])
plt.plot([0, 1], [0, 1], 'k--')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')

plt.title('Receiver operating characteristic example')
plt.legend(loc="lower right")

plt.show()


[0.70289855 0.87681159 0.92028986 0.76086957 0.86231884]
[0.68115942 0.96376812 0.88405797 0.79710145 0.89855072]
[0.65217391 0.97101449 0.89130435 0.76086957 0.87681159]
[0.66666667 0.96376812 0.9057971  0.76086957 0.9057971 ]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed